"""crear tablas iniciales

Revision ID: fe9f3554bedb
Revises: 
Create Date: 2026-08-15 00:32:17.603727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe9f3554bedb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apostadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('partidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deporte', sa.String(length=50), nullable=False),
    sa.Column('liga', sa.String(length=100), nullable=False),
    sa.Column('equipo_local', sa.String(length=100), nullable=False),
    sa.Column('equipo_visitante', sa.String(length=100), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estado', sa.Enum('PROGRAMADO', 'EN_JUEGO', 'FINALIZADO', name='estado_partido'), nullable=False),
    sa.Column('resultado_local', sa.Integer(), nullable=True),
    sa.Column('resultado_visitante', sa.Integer(), nullable=True),
    sa.CheckConstraint('equipo_local <> equipo_visitante', name='ck_partido_equipos_distintos'),
    sa.CheckConstraint('resultado_local IS NULL OR resultado_local >= 0', name='ck_partido_resultado_local_no_negativo'),
    sa.CheckConstraint('resultado_visitante IS NULL OR resultado_visitante >= 0', name='ck_partido_resultado_visitante_no_negativo'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predicciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apostador_id', sa.Integer(), nullable=False),
    sa.Column('partido_id', sa.Integer(), nullable=False),
    sa.Column('goles_local_pred', sa.Integer(), nullable=False),
    sa.Column('goles_visitante_pred', sa.Integer(), nullable=False),
    sa.Column('fecha_prediccion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acertada', sa.Boolean(), nullable=True),
    sa.Column('puntos', sa.Integer(), nullable=True),
    sa.CheckConstraint('goles_local_pred >= 0', name='ck_prediccion_goles_local_no_negativo'),
    sa.CheckConstraint('goles_visitante_pred >= 0', name='ck_prediccion_goles_visitante_no_negativo'),
    sa.ForeignKeyConstraint(['apostador_id'], ['apostadores.id'], ),
    sa.ForeignKeyConstraint(['partido_id'], ['partidos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apostador_id', 'partido_id', name='uq_prediccion_apostador_partido')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predicciones')
    op.drop_table('partidos')
    op.drop_table('apostadores')
    # ### end Alembic commands ###
